randoop/randoop

doc/CHANGES.txt, doc/index.html, src/randoop/operation/ArrayCreation.java, src/randoop/operation/FinalInstanceField.java, src/randoop/operation/PublicField.java, src/randoop/operation/PublicFieldParser.java, src/randoop/sequence/VariableRenamer.java, src/randoop/util/Reflection.java, tests/randoop/operation/ArrayCreationTests.java
This fixes two things:
1) the mismatch between variable names for arrays where declared variable had additional "_array".
2) the omission of final instance variables from the PublicField hierarchy. Final instance variables were being treated as mutable.
user doc and version numbers updated to v.2.0.1
=> Fix array variable name and final instance field omission

doc/index.html, src/randoop/main/Main.java, src/randoop/sequence/SequenceExceptionError.java, src/randoop/test/ValidityCheckingVisitor.java
This PR:
1. always classifies a flaky OOM as an invalid test, rather than throwing an exception.
2. improves message for error output when flaky tests occur.
2. allows the user to turn off the strict intolerance for flaky tests using --ignore-flaky-tests.
3. changes defaults for forbid-null and null-ratio to false and 0.05.
=> A nicer shade of flaky

src/test/java/randoop/test/BiSort.java, src/test/java/randoop/test/bh/BH.java, src/test/java/randoop/test/health/Health.java, src/test/java/randoop/test/mst/MST.java, src/test/java/randoop/test/perimeter/Perimeter.java, src/test/java/randoop/test/treeadd/TreeAdd.java
This pull request is focused on resolving occurrences of Sonar rule 
squid:S2131 - “Primitives should not be boxed just for "String" conversion”. You can find more information about the issue here: 
https://dev.eclipse.org/sonar/rules/show/squid:S2131
Please let me know if you have any questions.
Ayman Abdelghany.
=> Primitives should not be boxed just for "String" conversion

src/test/java/randoop/test/bh/MathVector.java, src/test/java/randoop/test/symexamples/AbstractMap.java, src/testinput/java/java2/util2/AbstractCollection.java, src/testinput/java/java2/util2/AbstractMap.java, src/testinput/java/java2/util2/BitSet.java, src/testinput/java/java2/util2/Hashtable.java, src/testinput/java/ps1/RatPoly.java
This pull request is focused on resolving occurrences of Sonar rule 
squid:S1149 - “Synchronized classes Vector, Hashtable, Stack and StringBuffer should not be used ”. You can find more information about the issue here: 
https://dev.eclipse.org/sonar/rules/show/squid:S1149
Please let me know if you have any questions.
Ayman Abdelghany.
=> Synchronized classes Vector, Hashtable, Stack and StringBuffer should not be used

doc/dev.html, lib/README
Some comments that I did not address but that should perhaps be added:
In the "Randoop classpath" section:
"It is recommended that the classpath for classes under test be placed before
Plume-lib."
Please explain why, and more importantly give an example of how to achieve this.  Should the given text appear at the end of the classpath?
The alternative of using the "-all" jar file is not mentioned; wouldn't that be an easier modification of one's classpath?
=> Review of first half of developer manual

src/main/java/randoop/output/RandoopOutputException.java
The redundant `@param message the error message` in the method doc of constructor `randoop.output.RandoopOutputException(IOException cause)` is regarded as an error by `javadoc`.
It blocks compiling randoop from a clean clone.
=> Remove redundant, compile-blocking @param from doc

src/main/java/randoop/output/JUnitCreator.java, src/main/java/randoop/test/CompilableTestPredicate.java, src/main/java/randoop/test/ExpectedExceptionCheck.java
terminate on parse error if debug-checks is set.  my limited testing showed no significant performance cost for --debug-checks.  We could use for in-house testing and default behavior would be unchanged.
correct parse error with embedded quotes (")
=> parser fixes

src/docs/CHANGES.txt, src/docs/manual/index.html, src/main/java/randoop/main/GenInputsAbstract.java, src/main/java/randoop/main/GenTests.java, src/main/java/randoop/output/FailingTestFilter.java, src/systemtest/java/randoop/main/RandoopSystemTest.java
Unsure about the error message output in FailingTestFilter.  You suggested "See section #nondeterminism-inprogram-under-test ...".  Not sure if that was literal or implied some sort of href to the manual.
=> new flaky-test-behavior option (supersedes ignore-flaky-tests)

agent/replacecall/src/main/java/randoop/mock/java/util/MockRandom.java, agent/replacecall/src/main/resources/default-replacements.txt, src/docs/manual/index.html
Adds default replacements for the class `java.util.Random`, for instance methods such as `nextInt()`, `nextDouble()`, `nextFloat()`, and `nextLong()`.  This is necessary because Randoop does not yet support replacing constructor calls.
A small test case with an example class and the command is located here:
https://github.com/huangwaylon/test_randoop
=> Replace calls to instance methods of java.util.Random

src/main/java/randoop/types/ClassOrInterfaceType.java
Perhaps a better fix is to get the generic interfaces of a class.
=> Change isSubtype so raw Comparable is a subtype of Comparable<T>

src/docs/CHANGES.txt, src/docs/manual/index.html, src/main/java/randoop/main/GenInputsAbstract.java, src/main/java/randoop/output/FailingTestFilter.java, src/systemtest/java/randoop/main/RandoopOptions.java
Improve output even when it is not set.
Set it by default in system tests, to make Travis failures easier to debug.
=>  Rename --print-file-system-state to --print-erroneous-file

agent/replacecall/src/main/java/randoop/instrument/CallReplacementTransformer.java
Enable deubg logging now that SimpleLog supports output to file.
Improve documentation and handling of exceptions.
=> Enable debug logging in CallReplaceTransformer

src/main/java/randoop/main/GenTests.java
=> Cache result of `FileSystems.newFileSystem`; fixes #355

src/main/java/randoop/contract/ObjectContractUtils.java
I have tried running Randoop 4.2.6 on a set of classes in Spark 3.2.0 and encountered the following issue.
```
scala.collection.generic.GenTraversableFactory.GenericCanBuildFrom<scala.runtime.Nothing$> nothing$GenericCanBuildFrom0 = scala.collection.Seq.ReusableCBF(); // [NormalExecution scala.collection.generic.GenTraversableFactory$$anon$1@6bc246c0 [class scala.collection.generic.GenTraversableFactory$$anon$1]]
<randoop.contract.IsNotNull@1f [nothing$GenericCanBuildFrom0]>
randoop.main.RandoopBug: Problem with ObjectCheck <randoop.contract.IsNotNull@1f [nothing$GenericCanBuildFrom0]>
at randoop.test.ObjectCheck.toCodeStringPostStatement(ObjectCheck.java:99)
at randoop.sequence.ExecutableSequence.toCodeLines(ExecutableSequence.java:186)
at …
```
=> Support escaping dollar sign from variable name

src/docs/manual/index.html
Change `--methodList` to `--methodlist`.
=> Fix typo in manual

src/main/java/randoop/output/JUnitCreator.java
change System.exit(1) to Runtime.getRuntime().exit(1) to avoid conflict with replacecall
=> fix RegressionTestDriver problem

build.gradle
Make sure the the Checker Framework plugin uses the same version of the Checker Framework that is used as a dependencies of the project.  This should fix the failures in #1238 and #1237.
=> Unify Checker Framework versions.

src/main/java/randoop/contract/CompareToEquals.java
StringBuilder implements the Comparable interface. However, it does not override the equals method. This causes a false contract failure when this check is performed on StringBuilder. The changes are that the contract will always evaluate to true if it involves a StringBuilder.
=> CompareToEquals ignores StringBuilder check

src/main/java/randoop/generation/ForwardGenerator.java
Using randoop, i could observe that setting forbid-null=true does not forbid null actually. Adding this change in the if statement condition does it.
=> Add forbid null flag (#1344)

src/main/java/randoop/types/NonParameterizedType.java
This caused an issue when using demand driven on the easymock library.
=> Check if superclass is enum in isEnum method. 

build.gradle
After unzip the current release file [randoop-4.3.4.zip](https://github.com/randoop/randoop/releases/download/v4.3.4/randoop-4.3.4.zip), a directory named `extension 'base' property 'archivesName'-4.3.4` will be created.
This PR fixes the `build.gradle` to correctly set the name. With the fix, unzipping `randoop-4.3.4.zip` will create a dir named `randoop-4.3.4`.
=> Fix directory name for the distribution zip
